### PR TITLE
Improve sniper textures

### PR DESCRIPTION
**Pull request by LoneWolfHT**
* Texture size is now 32x32
* wield_scale is now basically double, so wield pixels will be the same size as that of other wielded items
* Inventory texture still looks out of place but is a little better I think

image

image

image

### CODE REVIEW

**Comment by ClobberXD** [comment]
Looks pretty good! Will test today.

**Comment by ClobberXD** [comment]
The new texture for the 7.62 rifle looks pretty spot on, nice. But I notice that you've gone for a bent-stock design for the Magnum rifle as well, similar to the 7.62 rifle. This stock style doesn't fit the more powerful Magnum rifle, IMO, and isn't the style I was originally going for either. It'd be nice if you could change the stock to something similar-looking to the original texture. I'm ok with the colours though. For reference, here's the look I'm going for: https://en.wikipedia.org/wiki/Accuracy_International_AWM 

EDIT:

**Comment by LoneWolfHT** [comment]
I didn't realize you were going for anything lol. Was just drawing sniper rifles. How's this?

image
#
image

**Comment by LoneWolfHT** [comment]
RIP, that magnum pic is a pixel off, I removed a pixel below the trigger
image

**Comment by ClobberXD** [comment]
Much better. It'd be nice if you could make the stock a _little_ taller though. The top edge of the stock is perfect, but the lower edge could be lowered a pixel or two.

**Comment by LoneWolfHT** [comment]
How much farther? 
image

**Comment by ClobberXD** [comment]
This is how I'd prefer it to be:

(Disclaimer: I'm not responsible if you die from seeing this)

Untitled

Notice the height difference between the fore-end (the part in front of the trigger) and the stock.

**Comment by LoneWolfHT** [comment]
image
image

**Comment by ClobberXD** [comment]
Purrrrfecto :+1:

**Review by ClobberXD — APPROVED** [review]

**Pull request merged**
